# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install Dependencies
      run: npm ci
      working-directory: /home/ubuntu/frontend/_work/frontend/frontend/my-react-app/
    
    - name: Build Project
      run: npm run build --if-present
      working-directory: /home/ubuntu/frontend/_work/frontend/frontend/my-react-app/
    
    - name: Build Project (Second Command)
      run: npm run build
      working-directory: /home/ubuntu/frontend/_work/frontend/frontend/my-react-app/

